source "https://rubygems.org"

gemspec

gem "chef_backup", git: "https://github.com/chef/chef_backup.git"
gem "omnibus-ctl", git: "https://github.com/chef/omnibus-ctl.git"
gem "veil", git: "https://github.com/chef/chef_secrets.git"
gem "toml" # for habitat-land

# remove these once we have released chef 15; we can go back to using gems
gem "chef", git: "https://github.com/chef/chef.git", branch: "v15.0.269"
gem "ohai", git: "https://github.com/chef/ohai.git"



